# This playbook is to be used to generate spine MP-BGP config with variables from underlay.yml
# Additionally creates the overlay configuration
---
- hosts: spines_DC2
  gather_facts: no
  tasks:
    - name: Register variables (candidates- Do not change this)
      include_vars:
        file: "{{ lookup('env','PWD') }}/vars/underlay.yml"
        name: underlay
    - name: Register variables (candidates- Do not change this)
      include_vars:
        file: "{{ lookup('env','PWD') }}/vars/overlay.yml"
        name: overlay

    - name: Create underlay configurations
      template:
        src: "{{ lookup('env','PWD') }}/templates/spine.j2"
        dest: "{{ lookup('env','PWD') }}/configs/{{inventory_hostname}}_spine_underlay.cfg"
    - name: Create overlay configurations
      template:
        src: "{{ lookup('env','PWD') }}/templates/spine_overlay.j2"
        dest: "{{ lookup('env','PWD') }}/configs/{{inventory_hostname}}_spine_overlay.cfg"
  # Use the eos_config module to create a task to upload the configuration you created to the switch
  
    - name: "Deploy EOS configurations"
      arista.eos.eos_config:
        backup: yes
        backup_options:
          dir_path: "{{ lookup('env', 'PWD') }}/backups/"
          filename: "{{ inventory_hostname }}.cfg"
        save_when: changed
        src: "{{ lookup('env', 'PWD') }}/templates/spine.j2"
    - name: "Deploy EOS configurations"
      arista.eos.eos_config:
        backup: yes
        backup_options:
          dir_path: "{{ lookup('env', 'PWD') }}/backups/"
          filename: "{{ inventory_hostname }}.cfg"
        save_when: changed
        src: "{{ lookup('env', 'PWD') }}/templates/spine_overlay.j2"
